name: deploy-web
on:
  push:
    branches:
      - main

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: s-weigand/setup-conda@v1
      - run: conda --version
      - run: which python

      - name: Install dependencies
        run: |
          pip install sanic

      # Build the book
      - name: Build the web
        run: |
          sanic server.app

      # # Deploy the book's HTML to gh-pages branch
      # - name: GitHub Pages action
      #   uses: peaceiris/actions-gh-pages@v3.6.1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
